---
title: "Tidy Data"
output: github_document
---

```{r setup}
library(tidyverse) #ggplot, readr, tibble
```

## `pivot_longer`

Load the PULSE data

```{r}
pulse_data = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") %>% 
  janitor::clean_names()
```


Wide format to long format ...


```{r}
pulse_data_tidy = 
  pulse_data %>% 
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    names_prefix = "bdi_score_",
    values_to = "bdi"
  )
#names_prefix	:A regular expression used to remove matching text from the start of each variable name.
```

rewrite, combine, and extend(to add a mutate)
```{r}
#relocate(xxx,yyy)把xxx，yyy按顺序提前
#mutate(想改变的对象（variable） = recode(想改变的对象，“想要被替代的内容” = “想要的内容"))
pulse_data = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    names_prefix = "bdi_score_",
    values_to = "bdi"
  ) %>% 
  relocate(id, visit) %>% 
  mutate(visit = recode(visit, "bl" = "00m"))
```


##`pivot_wider`

Make up some data!

```{r}
analysis_result = 
  tibble(
    group = c("treatment", "treatment", "placebo", "placebo"),
    time = c("pre", "post", "pre", "post"),
    mean = c(4, 8, 3.5, 4)
  )

analysis_result %>% 
  pivot_wider(
    names_from = "time",
    values_from ="mean"
  )
```

## Binding rows
stack different tables together
Usin the LotR data.

First step: import each table
```{r}
#这里面的mutate加了一个名叫new column， mutate(new column name = "new column value")
fellowship_ring = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "B3:D6") %>% 
  mutate(movie = "fellowship_ring")

two_towers= 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "F3:H6") %>% 
  mutate(movie = "two_towers")

return_king = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "J3:L6") %>% 
  mutate(movie = "return_king")
```


Bine all the rows together

```{r}
lotr_tidy = 
  bind_rows(fellowship_ring, two_towers, return_king) %>% 
  janitor::clean_names() %>% 
  relocate(movie) %>% 
  pivot_longer(
    female:male,
    names_to = "gender",
    values_to = "words"
  )
```



